version: '3.7'
services:
  mssql-container:
    container_name: mssql-container
    image: mcr.microsoft.com/mssql/server:2019-latest  
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Abc1234567890@"
    ports:
    networks:
      - moviebooker-network
  redis-container:
    image: docker.io/redis:7.2.3
    container_name: redis-container
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - ./redis-data:/data
    networks:
      - moviebooker-network
networks:
  moviebooker-network:
    name: moviebooker-network
    driver: bridge


#docker-compose -f ./deployment.yaml rm -s -f mssql-container
#docker-compose -f ./deployment.yaml up -d mssql-container

#docker-compose -f ./deployment.yaml rm -s -f redis-container
#docker-compose -f ./deployment.yaml up -d redis-container